FROM python:3.11-slim

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn

WORKDIR /app
COPY api_tools/server.py /app/server.py

CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
